# yaml-language-server: $schema=https://json.schemastore.org/github-workflow.json
name: Deploy SFE-Frontend to Vercel

on:
  workflow_dispatch:
  push:
    branches: [main, develop]

jobs:
  deploy:
    runs-on: ubuntu-latest
    if: "!contains(github.event.head_commit.message, '[skip ci]')"
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - uses: dorny/paths-filter@v2
        id: changes
        with:
          filters: |
            contracts:
              - 'packages/frontend-sfe/**'

      - name: Deploy to Preview
        uses: BetaHuhn/deploy-to-vercel-action@v1.9.0
        if: github.event_name == 'workflow_dispatch'
        with:
          GITHUB_TOKEN: ${{ secrets.GH_PAT }}
          VERCEL_TOKEN: ${{ secrets.VERCEL_TOKEN }}
          VERCEL_ORG_ID: ${{ secrets.VERCEL_ORG_ID }}
          VERCEL_PROJECT_ID: ${{ secrets.VERCEL_PROJECT_ID_SFE }}
          ALIAS_DOMAINS: |
            stake-for-earth-{SHA}.vercel.app
          PRODUCTION: false
          GITHUB_DEPLOYMENT_ENV: Preview
          FORCE: true

      - name: Deploy to Staging
        uses: BetaHuhn/deploy-to-vercel-action@v1.9.0
        if: github.event_name == 'push' && github.ref == 'refs/heads/develop' && steps.changes.outputs.contracts == 'true'
        with:
          GITHUB_TOKEN: ${{ secrets.GH_PAT }}
          VERCEL_TOKEN: ${{ secrets.VERCEL_TOKEN }}
          VERCEL_ORG_ID: ${{ secrets.VERCEL_ORG_ID }}
          VERCEL_PROJECT_ID: ${{ secrets.VERCEL_PROJECT_ID_SFE }}
          ALIAS_DOMAINS: |
            stake-for-earth-dev.vercel.app
          PRODUCTION: false
          GITHUB_DEPLOYMENT_ENV: Staging
          FORCE: true

      - name: Deploy to Production
        uses: BetaHuhn/deploy-to-vercel-action@v1.9.0
        if: github.event_name == 'push' && github.ref == 'refs/heads/main' && steps.changes.outputs.contracts == 'true'
        with:
          GITHUB_TOKEN: ${{ secrets.GH_PAT }}
          VERCEL_TOKEN: ${{ secrets.VERCEL_TOKEN }}
          VERCEL_ORG_ID: ${{ secrets.VERCEL_ORG_ID }}
          VERCEL_PROJECT_ID: ${{ secrets.VERCEL_PROJECT_ID_SFE }}
          PRODUCTION: true
          GITHUB_DEPLOYMENT_ENV: Production
          FORCE: true
